In [1]:

# Assigning Subsequent Rows to Matrix first row elements

test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]


print("The original list : " + str(test_list))

res = dict(zip(test_list[0], test_list[1:]))


print("The Assigned Matrix : " + str(res))

The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])

print("Print elements of first matrix")
print(A)
print("Print elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A,B))

Print elements of first matrix
[[1 2]
 [3 4]]
Print elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [5]:
from itertools import groupby

test_list = [1, 1, 2, 3, 3, 3]
for key, group in groupby(test_list):
    print(key, list(group))


1 [1, 1]
2 [2]
3 [3, 3, 3]


In [6]:
test_list = [[('Gfg', 3)], [('best', 1)]]
list1 = [1, 2]


res = [[tup + (list1[i],) for tup in sublist] for i, sublist in enumerate(test_list)]

print(res)


[[('Gfg', 3, 1)], [('best', 1, 2)]]


In [3]:
def generate_matrix(n):
    num = 1
    matrix = []

    # Fill the matrix row by row
    for i in range(n):
        row = []
        for j in range(n):
            row.append(num)
            num += 1
        # Reverse every odd-indexed row (only if n is even)
        if n % 2 == 0 and i % 2 == 1:
            row.reverse()
        matrix.append(row)

    # Print the matrix
    for row in matrix:
        print(*row)

# Example usage
n = 4
generate_matrix(n)


1 2 3 4
8 7 6 5
9 10 11 12
16 15 14 13
